apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis
  labels:
    app: my-redis
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-redis
      env: prod
  template:
    metadata:
      labels:
        app: my-redis
        env: prod
    spec:
      containers:
      - name: my-redis
        image: redis:6.2.7
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - name: redis-default
            containerPort: 6379
            protocol: TCP
